import type { LucideIcon } from "lucide-react";
import {
  AlertTriangle,
  Battery,
  Car,
  CircleDot,
  CircleHelp,
  Compass,
  Cross,
  Droplets,
  Flame,
  Footprints,
  Fuel,
  HandHelping,
  HeartPulse,
  Home,
  KeyRound,
  MapPin,
  Mountain,
  Phone,
  Pill,
  Route,
  ShieldAlert,
  Siren,
  Trees,
  UserRound,
  Users,
  Wind,
  Wrench,
} from "lucide-react";
import type { HelpIconId } from "@/lib/help-taxonomy";

export const HELP_ICONS: Record<HelpIconId, LucideIcon> = {
  stuck: Car,
  lost: Compass,
  injured: Cross,
  unsafe: ShieldAlert,
  need: HandHelping,
  report: AlertTriangle,
  someone: Users,
  unknown: CircleHelp,
  fuel: Fuel,
  tire: CircleDot,
  battery: Battery,
  engine: Wrench,
  lock: KeyRound,
  terrain: Mountain,
  crash: Siren,
  walk: Footprints,
  drive: Car,
  hike: Trees,
  group: Users,
  directions: Route,
  missing: UserRound,
  bleed: Droplets,
  fall: UserRound,
  breath: Wind,
  chest: HeartPulse,
  burn: Flame,
  bone: Cross,
  unconscious: Cross,
  follow: UserRound,
  threat: ShieldAlert,
  home: Home,
  place: MapPin,
  silent: Phone,
  ride: Car,
  food: Droplets,
  medicine: Pill,
  shelter: Home,
  phone: Phone,
  tools: Wrench,
  hazard: AlertTriangle,
  fire: Flame,
  person: UserRound,
  suspicious: ShieldAlert,
  road: Route,
  help: HandHelping,
};
